package com.sesengine.wsdl.client.publicdirectorysearch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-09-16T23:36:14.321+05:30
 * Generated source version: 2.7.6
 *
 */
@WebService(targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", name = "DirectoryService")
@XmlSeeAlso({ObjectFactory.class})
public interface DirectoryService {

    @WebResult(name = "FindLocalUserResult", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
    @Action(input = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/FindLocalUser", output = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/FindLocalUserResponse")
    @RequestWrapper(localName = "FindLocalUser", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.FindLocalUser")
    @WebMethod(operationName = "FindLocalUser", action = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/FindLocalUser")
    @ResponseWrapper(localName = "FindLocalUserResponse", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.FindLocalUserResponse")
    public com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfSesAddress findLocalUser(
        @WebParam(name = "parameters", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
        com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfSearchParameter parameters
    );

    @WebResult(name = "GetAddressesByTrustGroupResult", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
    @Action(input = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/GetAddressesByTrustGroup", output = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/GetAddressesByTrustGroupResponse")
    @RequestWrapper(localName = "GetAddressesByTrustGroup", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.GetAddressesByTrustGroup")
    @WebMethod(operationName = "GetAddressesByTrustGroup", action = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/GetAddressesByTrustGroup")
    @ResponseWrapper(localName = "GetAddressesByTrustGroupResponse", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.GetAddressesByTrustGroupResponse")
    public com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfSesAddress getAddressesByTrustGroup(
        @WebParam(name = "domain", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
        java.lang.String domain
    );

    @WebResult(name = "ExternalDirectorySearchResult", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
    @Action(input = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/ExternalDirectorySearch", output = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/ExternalDirectorySearchResponse")
    @RequestWrapper(localName = "ExternalDirectorySearch", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.ExternalDirectorySearch")
    @WebMethod(operationName = "ExternalDirectorySearch", action = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/ExternalDirectorySearch")
    @ResponseWrapper(localName = "ExternalDirectorySearchResponse", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.ExternalDirectorySearchResponse")
    public com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfExternalSearchResponse externalDirectorySearch(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
        com.sesengine.wsdl.client.publicdirectorysearch.ExternalSearchRequest request
    );

    @Action(input = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/UpdateDirectoryCache", output = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/UpdateDirectoryCacheResponse")
    @RequestWrapper(localName = "UpdateDirectoryCache", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.UpdateDirectoryCache")
    @WebMethod(operationName = "UpdateDirectoryCache", action = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/UpdateDirectoryCache")
    @ResponseWrapper(localName = "UpdateDirectoryCacheResponse", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.UpdateDirectoryCacheResponse")
    public void updateDirectoryCache();

    @WebResult(name = "DNSCertLookupResult", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
    @Action(input = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/DNSCertLookup", output = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/DNSCertLookupResponse")
    @RequestWrapper(localName = "DNSCertLookup", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.DNSCertLookup")
    @WebMethod(operationName = "DNSCertLookup", action = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/DNSCertLookup")
    @ResponseWrapper(localName = "DNSCertLookupResponse", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.DNSCertLookupResponse")
    public byte[] dnsCertLookup(
        @WebParam(name = "email", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
        java.lang.String email
    );

    @WebResult(name = "PublicDirectorySearchResult", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
    @Action(input = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/PublicDirectorySearch", output = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/PublicDirectorySearchResponse")
    @RequestWrapper(localName = "PublicDirectorySearch", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.PublicDirectorySearch")
    @WebMethod(operationName = "PublicDirectorySearch", action = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/PublicDirectorySearch")
    @ResponseWrapper(localName = "PublicDirectorySearchResponse", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.PublicDirectorySearchResponse")
    public com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfPublicSearchResponse publicDirectorySearch(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
        com.sesengine.wsdl.client.publicdirectorysearch.PublicSearchRequest request
    );

    @WebResult(name = "getFullDirectoryListResult", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2")
    @Action(input = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/getFullDirectoryList", output = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/getFullDirectoryListResponse")
    @RequestWrapper(localName = "getFullDirectoryList", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.GetFullDirectoryList")
    @WebMethod(action = "http://secureexchangesolutions.com/2011/Directory/v2/DirectoryService/getFullDirectoryList")
    @ResponseWrapper(localName = "getFullDirectoryListResponse", targetNamespace = "http://secureexchangesolutions.com/2011/Directory/v2", className = "com.sesengine.wsdl.client.publicdirectorysearch.GetFullDirectoryListResponse")
    public com.sesengine.wsdl.client.publicdirectorysearch.GetFullDirectoryListResponse.GetFullDirectoryListResult getFullDirectoryList();
}
