package com.sesengine.wsdl.client.publicdirectorysearch;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-09-16T23:36:14.335+05:30
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "DirectoryServices", 
                  wsdlLocation = "http://service.directaddress.net/Directory2/DirectoryServices.svc?wsdl ",
                  targetNamespace = "http://tempuri.org/") 
public class DirectoryServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "DirectoryServices");
    public final static QName WSHttpBindingDirectoryService = new QName("http://tempuri.org/", "WSHttpBinding_DirectoryService");
    static {
        URL url = null;
        try {
            url = new URL("http://service.directaddress.net/Directory2/DirectoryServices.svc?wsdl ");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DirectoryServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/http://service.directaddress.net/Directory2/DirectoryServices.svc?wsdl ");
        }
        WSDL_LOCATION = url;
    }

    public DirectoryServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DirectoryServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectoryServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DirectoryServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DirectoryServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DirectoryServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DirectoryService
     */
    @WebEndpoint(name = "WSHttpBinding_DirectoryService")
    public DirectoryService getWSHttpBindingDirectoryService() {
        return super.getPort(WSHttpBindingDirectoryService, DirectoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectoryService
     */
    @WebEndpoint(name = "WSHttpBinding_DirectoryService")
    public DirectoryService getWSHttpBindingDirectoryService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingDirectoryService, DirectoryService.class, features);
    }

}
