
package com.sesengine.wsdl.client.publicdirectorysearch;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-09-16T23:36:14.270+05:30
 * Generated source version: 2.7.6
 *
 */
public final class DirectoryService_WSHttpBindingDirectoryService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "DirectoryServices");

    private DirectoryService_WSHttpBindingDirectoryService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DirectoryServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DirectoryServices ss = new DirectoryServices(wsdlURL, SERVICE_NAME);
        DirectoryService port = ss.getWSHttpBindingDirectoryService();

        {
        System.out.println("Invoking findLocalUser...");
        com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfSearchParameter _findLocalUser_parameters = null;
        com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfSesAddress _findLocalUser__return = port.findLocalUser(_findLocalUser_parameters);
        System.out.println("findLocalUser.result=" + _findLocalUser__return);


        }
        {
        System.out.println("Invoking getAddressesByTrustGroup...");
        java.lang.String _getAddressesByTrustGroup_domain = "";
        com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfSesAddress _getAddressesByTrustGroup__return = port.getAddressesByTrustGroup(_getAddressesByTrustGroup_domain);
        System.out.println("getAddressesByTrustGroup.result=" + _getAddressesByTrustGroup__return);


        }
        {
        System.out.println("Invoking externalDirectorySearch...");
        com.sesengine.wsdl.client.publicdirectorysearch.ExternalSearchRequest _externalDirectorySearch_request = null;
        com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfExternalSearchResponse _externalDirectorySearch__return = port.externalDirectorySearch(_externalDirectorySearch_request);
        System.out.println("externalDirectorySearch.result=" + _externalDirectorySearch__return);


        }
        {
        System.out.println("Invoking updateDirectoryCache...");
        port.updateDirectoryCache();


        }
        {
        System.out.println("Invoking dnsCertLookup...");
        java.lang.String _dnsCertLookup_email = "";
        byte[] _dnsCertLookup__return = port.dnsCertLookup(_dnsCertLookup_email);
        System.out.println("dnsCertLookup.result=" + _dnsCertLookup__return);


        }
        {
        System.out.println("Invoking publicDirectorySearch...");
        com.sesengine.wsdl.client.publicdirectorysearch.PublicSearchRequest _publicDirectorySearch_request = null;
        com.sesengine.wsdl.client.publicdirectorysearch.ArrayOfPublicSearchResponse _publicDirectorySearch__return = port.publicDirectorySearch(_publicDirectorySearch_request);
        System.out.println("publicDirectorySearch.result=" + _publicDirectorySearch__return);


        }
        {
        System.out.println("Invoking getFullDirectoryList...");
        com.sesengine.wsdl.client.publicdirectorysearch.GetFullDirectoryListResponse.GetFullDirectoryListResult _getFullDirectoryList__return = port.getFullDirectoryList();
        System.out.println("getFullDirectoryList.result=" + _getFullDirectoryList__return);


        }

        System.exit(0);
    }

}
