
package com.sesengine.wsdl.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SecureIntegrationServiceImap", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecureIntegrationServiceImap {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetMessageNumber", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/GetMessageNumber")
    @WebResult(name = "GetMessageNumberResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "GetMessageNumber", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessageNumber")
    @ResponseWrapper(localName = "GetMessageNumberResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessageNumberResponse")
    public Integer getMessageNumber(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        ReceiveRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetReadMessageNumber", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/GetReadMessageNumber")
    @WebResult(name = "GetReadMessageNumberResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "GetReadMessageNumber", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetReadMessageNumber")
    @ResponseWrapper(localName = "GetReadMessageNumberResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetReadMessageNumberResponse")
    public Integer getReadMessageNumber(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        ReceiveRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sesengine.wsdl.client.ArrayOfMessageSummary
     */
    @WebMethod(operationName = "GetMessageList", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/GetMessageList")
    @WebResult(name = "GetMessageListResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "GetMessageList", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessageList")
    @ResponseWrapper(localName = "GetMessageListResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessageListResponse")
    public ArrayOfMessageSummary getMessageList(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        ReceiveRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sesengine.wsdl.client.SesHeader
     */
    @WebMethod(operationName = "GetMessageHeader", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/GetMessageHeader")
    @WebResult(name = "GetMessageHeaderResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "GetMessageHeader", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessageHeader")
    @ResponseWrapper(localName = "GetMessageHeaderResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessageHeaderResponse")
    public SesHeader getMessageHeader(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        ReceiveRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sesengine.wsdl.client.SesMessage
     */
    @WebMethod(operationName = "GetMessage", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/GetMessage")
    @WebResult(name = "GetMessageResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "GetMessage", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessage")
    @ResponseWrapper(localName = "GetMessageResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.GetMessageResponse")
    public SesMessage getMessage(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        ReceiveRequest request);

    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMessage", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/SendMessage")
    @WebResult(name = "SendMessageResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.SendMessageResponse")
    public String sendMessage(
        @WebParam(name = "message", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        SesMessage message);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteMessage", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/DeleteMessage")
    @WebResult(name = "DeleteMessageResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "DeleteMessage", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.DeleteMessage")
    @ResponseWrapper(localName = "DeleteMessageResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.DeleteMessageResponse")
    public Boolean deleteMessage(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        ReceiveRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateMessageStatus", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/UpdateMessageStatus")
    @WebResult(name = "UpdateMessageStatusResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "UpdateMessageStatus", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.UpdateMessageStatus")
    @ResponseWrapper(localName = "UpdateMessageStatusResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.UpdateMessageStatusResponse")
    public Boolean updateMessageStatus(
        @WebParam(name = "request", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        ReceiveRequest request);

    /**
     * 
     * @param text
     * @param returnAddress
     * @param fromAddress
     * @param messageId
     * @param disposition
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMDN", action = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1/SecureIntegrationServiceImap/SendMDN")
    @WebResult(name = "SendMDNResult", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
    @RequestWrapper(localName = "SendMDN", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.SendMDN")
    @ResponseWrapper(localName = "SendMDNResponse", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1", className = "com.sesengine.wsdl.client.SendMDNResponse")
    public String sendMDN(
        @WebParam(name = "ReturnAddress", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        String returnAddress,
        @WebParam(name = "FromAddress", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        String fromAddress,
        @WebParam(name = "MessageId", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        String messageId,
        @WebParam(name = "Text", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        String text,
        @WebParam(name = "disposition", targetNamespace = "http://secureexchangesolutions.com/2012/SecureIntegrationServiceImap/v1")
        DispositionType disposition);

}
