
package com.sesengine.wsdl.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SecureIntegrationServicesImap", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://service.directaddress.net/Directory2/SecureIntegrationServicesImap.svc?wsdl")
public class SecureIntegrationServicesImap
    extends Service
{

    private final static URL SECUREINTEGRATIONSERVICESIMAP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sesengine.wsdl.client.SecureIntegrationServicesImap.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sesengine.wsdl.client.SecureIntegrationServicesImap.class.getResource(".");
            url = new URL(baseUrl, "https://service.directaddress.net/Directory2/SecureIntegrationServicesImap.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://service.directaddress.net/Directory2/SecureIntegrationServicesImap.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SECUREINTEGRATIONSERVICESIMAP_WSDL_LOCATION = url;
    }

    public SecureIntegrationServicesImap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecureIntegrationServicesImap() {
        super(SECUREINTEGRATIONSERVICESIMAP_WSDL_LOCATION, new QName("http://tempuri.org/", "SecureIntegrationServicesImap"));
    }

    /**
     * 
     * @return
     *     returns SecureIntegrationServiceImap
     */
    @WebEndpoint(name = "WSHttpBinding_SecureIntegrationServiceImap")
    public SecureIntegrationServiceImap getWSHttpBindingSecureIntegrationServiceImap() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_SecureIntegrationServiceImap"), SecureIntegrationServiceImap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecureIntegrationServiceImap
     */
    @WebEndpoint(name = "WSHttpBinding_SecureIntegrationServiceImap")
    public SecureIntegrationServiceImap getWSHttpBindingSecureIntegrationServiceImap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_SecureIntegrationServiceImap"), SecureIntegrationServiceImap.class, features);
    }

}
