/**
 *
 * Copyright 2012 by Nightingale, Inc.,
 * All rights reserved.
 * 
 * This software is the confidential and proprietary information
 * of Nightingale, Inc.
 *
 * This file has been automatically generated by CreateBean
 */
package com.nightingale.simplebeans;


import java.io.Serializable;

import com.google.gwt.user.client.rpc.IsSerializable;
import com.medrium.annotation.DBExcludeField;
import com.medrium.annotation.DBTableMap;
import com.medrium.xmlclient.annotation.XMLRPCIgnore;
import com.nightingale.annotation.AuditLabelProvider;

@DBTableMap (
        tableName="",
        primaryKeys={}
)
public class BaseTableInfo implements IsSerializable, Cloneable, BaseTable, Serializable {
    private String _ipaddress;
    private java.sql.Timestamp _created;
    @AuditLabelProvider(DataGroupNames.User)
    private String _createdby;
    private java.sql.Timestamp lastupdated;
    private String _updatedbyname;
    private String _originDataBeanHash;
    private String _newDataBeanHash;
    private String _credentials;
    
    @DBExcludeField
    @XMLRPCIgnore
    public String getOriginDataBeanHash() {return _originDataBeanHash;}
    public void setOriginDataBeanHash(String originDataBeanHash) {this._originDataBeanHash = originDataBeanHash;}
    @DBExcludeField
    @XMLRPCIgnore
    public String getNewDataBeanHash() {return _newDataBeanHash;}
    public void setNewDataBeanHash(String newDataBeanHash) {this._newDataBeanHash = newDataBeanHash;}
    @Override
    public java.sql.Timestamp getLastUpdated() {
        return lastupdated;
    }
    @Override
    public void setLastUpdated(java.sql.Timestamp lastupdated) {
        this.lastupdated = lastupdated;
    }
    @AuditLabelProvider(DataGroupNames.User)
    private String _updatedby;

    @Override
    @XMLRPCIgnore
    public String getIpAddress() { return  _ipaddress;} 
    @Override
    public void setIpAddress(String id) { _ipaddress=  id; }
    
    @Override
    public java.sql.Timestamp getCreated() { return  _created;}
    @Override
    public void setCreated(java.sql.Timestamp id) { _created=  id; }

    @Override
    public String getCreatedBy() { return  _createdby;}
    @Override
    public void setCreatedBy(String id) { _createdby=  id; }


    @Override
    public String getUpdatedBy() { return  _updatedby;}
    @Override
    public void setUpdatedBy(String id) { _updatedby=  id; }
    
    @Override
    @DBExcludeField(excludeInsert=true, excludeSelect=true, excludeUpdate=true)
    @XMLRPCIgnore
    public String getUpdatedByName() { return  _updatedbyname;} 
    @Override
    @DBExcludeField(excludeInsert=true, excludeSelect=true, excludeUpdate=true)
    public void setUpdatedByName(String id) { _updatedbyname=  id; }
    
    public BaseTableInfo(){        
    }
    
    /*
     * Copy constructor used for clone()
     */
    public BaseTableInfo(BaseTableInfo bti){
        this(bti.getIpAddress(), bti.getCreated(), bti.getCreatedBy(), bti.getLastUpdated(), bti.getUpdatedBy(), bti.getUpdatedByName());
    }
    /*
     * Copy constructor used for clone()
     */
    public BaseTableInfo(String ipAddress, java.sql.Timestamp created, String createdBy, java.sql.Timestamp lastUpdated, String updatedBy, String updatedByName){
        this.setCreated(created);
        this.setCreatedBy(createdBy);
        this.setIpAddress(ipAddress);
        this.setLastUpdated(lastUpdated);
        this.setUpdatedBy(updatedBy);
        this.setUpdatedByName(updatedByName);
    }
    
    /*
     * GWT workaround for clone, do not add @Override annotation, do not call super.clone(), copy constructor is the best option.
     */
    protected Object clone(){
        return new BaseTableInfo(this);
    }
    @DBExcludeField
    public boolean hasChanged()
    {
        
    if(this._originDataBeanHash == null && this._newDataBeanHash == null){
        return false;
        }
    
    if(this._originDataBeanHash == null){
        return true;
        }
    
    if(this._newDataBeanHash == null){
           return true;
           }
    
    return !this._originDataBeanHash.equals(this._newDataBeanHash);

    }
    
    
    @DBExcludeField
    @XMLRPCIgnore
    public String getCredentials(){    	return _credentials;    }
    public void setCredentials(String credentials){    	_credentials=credentials;    }

}
