//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.22 at 05:14:23 PM IST 
//


package com.ccd.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             Mailing and home or office addresses. A sequence of
 *             address parts, such as street or post office Box, city,
 *             postal code, country, etc.
 *          
 * 
 * <p>Java class for AD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AD">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}ANY">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="delimiter" type="{urn:hl7-org:v3}adxp.delimiter"/>
 *           &lt;element name="country" type="{urn:hl7-org:v3}adxp.country"/>
 *           &lt;element name="state" type="{urn:hl7-org:v3}adxp.state"/>
 *           &lt;element name="county" type="{urn:hl7-org:v3}adxp.county"/>
 *           &lt;element name="city" type="{urn:hl7-org:v3}adxp.city"/>
 *           &lt;element name="postalCode" type="{urn:hl7-org:v3}adxp.postalCode"/>
 *           &lt;element name="streetAddressLine" type="{urn:hl7-org:v3}adxp.streetAddressLine"/>
 *           &lt;element name="houseNumber" type="{urn:hl7-org:v3}adxp.houseNumber"/>
 *           &lt;element name="houseNumberNumeric" type="{urn:hl7-org:v3}adxp.houseNumberNumeric"/>
 *           &lt;element name="direction" type="{urn:hl7-org:v3}adxp.direction"/>
 *           &lt;element name="streetName" type="{urn:hl7-org:v3}adxp.streetName"/>
 *           &lt;element name="streetNameBase" type="{urn:hl7-org:v3}adxp.streetNameBase"/>
 *           &lt;element name="streetNameType" type="{urn:hl7-org:v3}adxp.streetNameType"/>
 *           &lt;element name="additionalLocator" type="{urn:hl7-org:v3}adxp.additionalLocator"/>
 *           &lt;element name="unitID" type="{urn:hl7-org:v3}adxp.unitID"/>
 *           &lt;element name="unitType" type="{urn:hl7-org:v3}adxp.unitType"/>
 *           &lt;element name="careOf" type="{urn:hl7-org:v3}adxp.careOf"/>
 *           &lt;element name="censusTract" type="{urn:hl7-org:v3}adxp.censusTract"/>
 *           &lt;element name="deliveryAddressLine" type="{urn:hl7-org:v3}adxp.deliveryAddressLine"/>
 *           &lt;element name="deliveryInstallationType" type="{urn:hl7-org:v3}adxp.deliveryInstallationType"/>
 *           &lt;element name="deliveryInstallationArea" type="{urn:hl7-org:v3}adxp.deliveryInstallationArea"/>
 *           &lt;element name="deliveryInstallationQualifier" type="{urn:hl7-org:v3}adxp.deliveryInstallationQualifier"/>
 *           &lt;element name="deliveryMode" type="{urn:hl7-org:v3}adxp.deliveryMode"/>
 *           &lt;element name="deliveryModeIdentifier" type="{urn:hl7-org:v3}adxp.deliveryModeIdentifier"/>
 *           &lt;element name="buildingNumberSuffix" type="{urn:hl7-org:v3}adxp.buildingNumberSuffix"/>
 *           &lt;element name="postBox" type="{urn:hl7-org:v3}adxp.postBox"/>
 *           &lt;element name="precinct" type="{urn:hl7-org:v3}adxp.precinct"/>
 *         &lt;/choice>
 *         &lt;element name="useablePeriod" type="{urn:hl7-org:v3}SXCM_TS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isNotOrdered" type="{urn:hl7-org:v3}bl" />
 *       &lt;attribute name="use" type="{urn:hl7-org:v3}set_PostalAddressUse" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AD", propOrder = {
    "delimiterOrCountryOrState",
    "useablePeriod"
})
public class AD
    extends ANY
{

    @XmlElements({
        @XmlElement(name = "deliveryAddressLine", namespace = "urn:hl7-org:v3", required = true, type = AdxpDeliveryAddressLine.class),
        @XmlElement(name = "streetNameBase", namespace = "urn:hl7-org:v3", required = true, type = AdxpStreetNameBase.class),
        @XmlElement(name = "country", namespace = "urn:hl7-org:v3", required = true, type = AdxpCountry.class),
        @XmlElement(name = "streetAddressLine", namespace = "urn:hl7-org:v3", required = true, type = AdxpStreetAddressLine.class),
        @XmlElement(name = "deliveryInstallationType", namespace = "urn:hl7-org:v3", required = true, type = AdxpDeliveryInstallationType.class),
        @XmlElement(name = "houseNumber", namespace = "urn:hl7-org:v3", required = true, type = AdxpHouseNumber.class),
        @XmlElement(name = "direction", namespace = "urn:hl7-org:v3", required = true, type = AdxpDirection.class),
        @XmlElement(name = "postalCode", namespace = "urn:hl7-org:v3", required = true, type = AdxpPostalCode.class),
        @XmlElement(name = "deliveryInstallationArea", namespace = "urn:hl7-org:v3", required = true, type = AdxpDeliveryInstallationArea.class),
        @XmlElement(name = "delimiter", namespace = "urn:hl7-org:v3", required = true, type = AdxpDelimiter.class),
        @XmlElement(name = "county", namespace = "urn:hl7-org:v3", required = true, type = AdxpCounty.class),
        @XmlElement(name = "additionalLocator", namespace = "urn:hl7-org:v3", required = true, type = AdxpAdditionalLocator.class),
        @XmlElement(name = "city", namespace = "urn:hl7-org:v3", required = true, type = AdxpCity.class),
        @XmlElement(name = "deliveryMode", namespace = "urn:hl7-org:v3", required = true, type = AdxpDeliveryMode.class),
        @XmlElement(name = "unitType", namespace = "urn:hl7-org:v3", required = true, type = AdxpUnitType.class),
        @XmlElement(name = "streetNameType", namespace = "urn:hl7-org:v3", required = true, type = AdxpStreetNameType.class),
        @XmlElement(name = "streetName", namespace = "urn:hl7-org:v3", required = true, type = AdxpStreetName.class),
        @XmlElement(name = "precinct", namespace = "urn:hl7-org:v3", required = true, type = AdxpPrecinct.class),
        @XmlElement(name = "houseNumberNumeric", namespace = "urn:hl7-org:v3", required = true, type = AdxpHouseNumberNumeric.class),
        @XmlElement(name = "unitID", namespace = "urn:hl7-org:v3", required = true, type = AdxpUnitID.class),
        @XmlElement(name = "deliveryModeIdentifier", namespace = "urn:hl7-org:v3", required = true, type = AdxpDeliveryModeIdentifier.class),
        @XmlElement(name = "state", namespace = "urn:hl7-org:v3", required = true, type = AdxpState.class),
        @XmlElement(name = "postBox", namespace = "urn:hl7-org:v3", required = true, type = AdxpPostBox.class),
        @XmlElement(name = "buildingNumberSuffix", namespace = "urn:hl7-org:v3", required = true, type = AdxpBuildingNumberSuffix.class),
        @XmlElement(name = "deliveryInstallationQualifier", namespace = "urn:hl7-org:v3", required = true, type = AdxpDeliveryInstallationQualifier.class),
        @XmlElement(name = "censusTract", namespace = "urn:hl7-org:v3", required = true, type = AdxpCensusTract.class),
        @XmlElement(name = "careOf", namespace = "urn:hl7-org:v3", required = true, type = AdxpCareOf.class)
    })
    protected List<ADXP> delimiterOrCountryOrState;
    @XmlElement(namespace = "urn:hl7-org:v3", required = true)
    protected List<SXCMTS> useablePeriod;
    @XmlAttribute
    protected Boolean isNotOrdered;
    @XmlAttribute
    protected List<String> use;
    

    /**
     * Gets the value of the delimiterOrCountryOrState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimiterOrCountryOrState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimiterOrCountryOrState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdxpDeliveryAddressLine }
     * {@link AdxpStreetNameBase }
     * {@link AdxpCountry }
     * {@link AdxpStreetAddressLine }
     * {@link AdxpDeliveryInstallationType }
     * {@link AdxpHouseNumber }
     * {@link AdxpDirection }
     * {@link AdxpPostalCode }
     * {@link AdxpDeliveryInstallationArea }
     * {@link AdxpDelimiter }
     * {@link AdxpCounty }
     * {@link AdxpAdditionalLocator }
     * {@link AdxpCity }
     * {@link AdxpDeliveryMode }
     * {@link AdxpUnitType }
     * {@link AdxpStreetNameType }
     * {@link AdxpStreetName }
     * {@link AdxpPrecinct }
     * {@link AdxpHouseNumberNumeric }
     * {@link AdxpUnitID }
     * {@link AdxpDeliveryModeIdentifier }
     * {@link AdxpState }
     * {@link AdxpPostBox }
     * {@link AdxpBuildingNumberSuffix }
     * {@link AdxpDeliveryInstallationQualifier }
     * {@link AdxpCensusTract }
     * {@link AdxpCareOf }
     * 
     * 
     */
    public List<ADXP> getDelimiterOrCountryOrState() {
        if (delimiterOrCountryOrState == null) {
            delimiterOrCountryOrState = new ArrayList<ADXP>();
        }
        return this.delimiterOrCountryOrState;
    }

    /**
     * Gets the value of the useablePeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the useablePeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUseablePeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SXCMTS }
     * 
     * 
     */
    public List<SXCMTS> getUseablePeriod() {
        if (useablePeriod == null) {
            useablePeriod = new ArrayList<SXCMTS>();
        }
        return this.useablePeriod;
    }

    /**
     * Gets the value of the isNotOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsNotOrdered() {
        return isNotOrdered;
    }

    /**
     * Sets the value of the isNotOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsNotOrdered(Boolean value) {
        this.isNotOrdered = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the use property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUse() {
        if (use == null) {
            use = new ArrayList<String>();
        }
        return this.use;
    }

}
